### ISSUE TITLE
colcon build fail

### ISSUE THREAD

**Issue by ambrosinim** [fmrico/aamcl#20]
--- stderr: mh_amcl                                                     
/home/luca/turtlebot3_ws/src/mh_amcl/src/mh_amcl/MH_AMCL.cpp:29:10: fatal error: tf2_geometry_msgs/tf2_geometry_msgs.hpp: No such file or directory
   29 | #include "tf2_geometry_msgs/tf2_geometry_msgs.hpp"

**Comment by fmrico** [comment]
Hi @ma-tesi 

What is your ROS distro? Before humble, this header is ".h" instead of ".hpp"

Best

**Comment by enterprisingWildDog** [comment]
hi, thanks for the reply. My distro is in fact galactic, I'll try to fix it and edit this post.
thanks

**Comment by fmrico** [comment]
If you need further assistance, please, don't hesitate to write more issues or even write me at fmrico@gmail.com

**Comment by enterprisingWildDog** [comment]
thanks, now it returns this when I build:

--- stderr: mh_amcl                               
/home/luca/turtlebot3_ws/src/mh_amcl/src/mh_amcl/MH_AMCL.cpp: In constructor ‘mh_amcl::MH_AMCL_Node::MH_AMCL_Node(const rclcpp::NodeOptions&)’:
/home/luca/turtlebot3_ws/src/mh_amcl/src/mh_amcl/MH_AMCL.cpp:54:26: error: no matching function for call to ‘nav2_util::LifecycleNode::LifecycleNode(const char [8], const char [1], const rclcpp::NodeOptions&)’

I am investigating on some issues with navigation2

**Comment by fmrico** [comment]
I am going to close this issue. It is compiled in Humble, at least.
